spring:
  application:
    name: auth-service

server:
  port: 8082
  servlet:
    context-path: /api/v1/auth

keycloak:
  server-url: http://localhost:8080
  realm: txnflow

  admin-realm: master
  admin-username: txn_admin
  admin-password: txn_strong
  admin-client-id: admin-cli
  client-secret: bNzXEcPNNToRvmavPSjxzthpqIwoELU4

logging:
  level:
    org.springframework.security: DEBUG