spring:
  application:
    name: notification-service

  web:
    resources:
      add-mappings: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KC_BASE_URL}/realms/txnflow

#  datasource:
#    url: jdbc:postgresql://localhost:5432/notification_db
#    username: txnflow
#    password: txnflow_password
#    hikari:
#      connection-timeout: 3000
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      enable-auto-commit: true
      properties:
        spring.json.type.mapping: walletCreditEvent:txnflow.notificationservice.dto.event.WalletCreditEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: "1"
      retries: 3

server:
  port: 8085
  servlet:
    context-path: /api/v1/notifications

resend:
  api-key: ${RESEND_API_KEY}

logging:
  level:
    org.springframework.security: info

management:
  endpoints:
    web:
      exposure:
        include: health,info

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: false
