spring:
  application:
    name: wallet-service
  web:
    resources:
      add-mappings: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_BASE_URL}/realms/txnflow

  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: txnflow
    password: txnflow_password
    hikari:
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
  servlet:
    context-path: /api/v1/wallets

logging:
  level:
    org.springframework.security: debug

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#
#  opentelemetry:
#    tracing:
#      export:
#        otlp:
#          endpoint: http://localhost:4318/v1/traces
#  otlp:
#    metrics:
#      export:
#        enabled: false